#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - config/*
    - config/environments/*
    - config/initializers/*
    - db/*
    - db/fixtures/**/*
    - db/migrate/*
    - db/seeds/*
    - lib/tasks/*
    - node_modules/**/*
    - Rakefile
    - tmp/**/*
    - vendor/**/*
    - bin/**/*

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

Semicolon:
  Enabled: false

# LAYOUT ##########
Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# METRICS ##########
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: true
  Max: 120

Metrics/ParameterLists:
  Enabled: true
  Max: 8

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 18

# RAILS ##########
Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# STYLE ##########
Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
#  EnforcedStyle: compact
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/SymbolArray:
  Enabled: false
