#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/*
    - db/migrate/*
    - config/*
    - config/environments/*
    - config/initializers/*
    - Gemfile
    - lib/tasks/*
    - Rakefile
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

Semicolon:
  Enabled: false

# LAYOUT ##########

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# METRICS ##########
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  Max: 8

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 18

# RAILS ##########

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

# STYLE ##########

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: false
