# As some lines need to be fairly long, line length is disabled
# Also, .html_safe is used on occasion so Rails/OutputSafety is disabled
# Other ignored_cops is the default list

AllCops:
  TargetRubyVersion: 2.5.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - db/*
      - db/migrate/*
      - config/*
      - config/environments/*
      - config/initializers/*
      - Gemfile
      - lib/tasks/*
      - Rakefile
      - 'vendor/**/*'
      - 'node_modules/**/*'
      - 'db/fixtures/**/*'
      - 'tmp/**/*'
      - 'bin/**/*'

linters:
  LineLength:
    enabled: false

  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/AlignHash
      - Layout/AlignParameters
      - Layout/FirstParameterIndentation
      - Layout/IndentationWidth
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/TrailingBlankLines
      - Layout/TrailingWhitespace
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/LineLength
      - Rails/OutputSafety
      - Style/BlockNesting
      - Style/FileName
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier
