# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37567518ddb5cc19229d32c9a233bddc33658c90ed2b4a1e9707c4f87c227f58dc3a7f315bef6550d5bfaad90053625a5472351f873b638bc95fc9e71399f2f1

test:
  secret_key_base: 09b0c697170cb80d6827d7376389654e10272ba7a12c401e9516de5ce94214304e534f39bca7acf9da83f7a5413e42975ca136dac3e8d2a18bb6dfbcc9c2d3a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
